# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GHD_Fast <- function(A, B) {
    .Call('DiffNet_GHD_Fast', PACKAGE = 'DiffNet', A, B)
}

MU_Fast <- function(A, B) {
    .Call('DiffNet_MU_Fast', PACKAGE = 'DiffNet', A, B)
}

STD_Fast <- function(A, B) {
    .Call('DiffNet_STD_Fast', PACKAGE = 'DiffNet', A, B)
}

